# MiBiPreT example: Data handling using Griftpark data

## Background: Griftpark contaminant site

Text to be added.

In [1]:
import mibiscreen as mbs

### Data handling

**Load in data:**

Returns loaded data as DataFrame which is reported when verbose flag is `True`.

In [2]:
file_path = './grift_BTEXIIN.csv'
data_raw,units = mbs.load_csv(file_path,verbose=True)
#print(type(data_raw))

================================================================
 Running function 'load_csv()' on data file  ./grift_BTEXIIN.csv
================================================================
Units of quantities:
-------------------
  sample nr obs_well well type Depth  pH     EC Redox  pE  NPOC sulfate  ...  \
0       NaN      NaN       NaN     m NaN  uS/cm    mV NaN  mg/L    mg/L  ...

  Propylbenzene M-Ethyltoluene O-Ethyltoluene 1,2,4-Trimethylbenzene  \
0          ug/L           ug/L           ug/L                   ug/L

  1,2,3-Trimethylbenzene Indane Indene Naphthalene metabolites_variety  \
0                   ug/L   ug/L   ug/L        ug/L                 NaN

  metabolites_concentration
0                      ug/L

[1 rows x 31 columns]
________________________________________________________________
Loaded data as pandas DataFrame:
--------------------------------
       sample nr           obs_well  well type      Depth    pH     EC Redox  \
0            NaN                NaN        NaN          m   NaN  uS/cm    mV
1   2019-031-001        A-32mm-52,5  dsn 32 mm      -52.5  7.31  149.8  -197
2   2019-031-002        A-32mm-65,5  dsn 32 mm      -65.5  7.35  147.8  -205
3   2019-031-009        B-MLS1-3-12      MLS-1        -12  7.23  133.9  -208
4   2019-031-011      B-MLS1-5-15,5      MLS-1      -15.5  7.67  125.1  -231
5   2019-031-012        B-MLS1-6-17      MLS-1        -17  7.75  156.5  -252
6   2019-031-013        B-MLS1-7-19      MLS-1        -19  7.53  161.8  -317
7   2019-031-014      B-MLS2-1-20,5      MLS-2      -20.5  7.34  159.4  -329
8   2019-031-018        B-MLS2-5-28      MLS-2        -28  7.25  149.8  -362
9   2019-031-020        B-MLS2-7-31      MLS-2        -31  7.21  155.5  -571
10  2019-031-004        B-32mm44-45  dsn 32 mm        -45  7.54  146.2  -187
11  2019-031-006       B-32mm-63-64  dsn 32 mm        -64  7.39   72.6  -175
12  2019-031-029        B2-MLS1-1-7      MLS-1         -7  7.09  141.9  -264
13  2019-031-031     B2-MLS1-3-10,5      MLS-1      -10.5  7.00  130.8  -253
14  2019-031-033       B2-MLS1-5-14      MLS-1        -14  7.00  115.1  -292
15  2019-031-034     B2-MLS1-6-15,5      MLS-1      -15.5  7.08  126.9  -244
16  2019-031-036       B2-MLS2-1-20      MLS-2        -20  7.31  123.3  -227
17  2019-031-039       B2-MLS2-4-43      MLS-2        -43  7.19  131.4  -183
18  2019-031-028  B2-32mm-64,5-65,5  dsn 40 mm      -65.5  7.66    131  -227
19  2019-031-048      C-MLS1-1-15,5      MLS-1      -15.5  7.70    138  -336
20  2019-031-050        C-MLS1-3-19      MLS-1        -19  7.48  143.5  -277
21  2019-031-054        C-MLS1-7-26      MLS-1        -26  7.33  140.9  -314
22  2019-031-044     C-32mm-38,5-39  dsn 32 mm        -39  8.26   81.1  -334
23  2019-031-047     C-32mm-45,5-46  dsn 32 mm        -46  7.52  165.9  -230
24  2019-031-059                Pb1        NaN  14,0-19,0  7.25  156.3  -182
25  2019-031-062                 60        NaN  68,0-72,0  7.31   78.1  -129
26  2019-031-063              BW205        NaN  43,0-45,0  7.29  105.1  -125

        pE   NPOC   sulfate  ... Propylbenzene M-Ethyltoluene O-Ethyltoluene  \
0      NaN   mg/L      mg/L  ...          ug/L           ug/L           ug/L
1   3.3293      6       203  ...             0              0              0
2   3.4645      7       166  ...             0              1              0
3   3.5152     19        23  ...            14              0             91
4   3.9039     20       NaN  ...            20            144             61
5   4.2588     16         1  ...            28             83             59
6   5.3573     13         9  ...            39             17             66
7   5.5601     12         5  ...            44              5             75
8   6.1178      9        79  ...            22             14             41
9   9.6499      8       127  ...             1              0              7
10  3.1603      7       237  ...             0              0              0
11  2.9575      4        39  ...             0              0              0
12  4.4616     19       176  ...            25            128             39
13  4.2757     15        42  ...            22              0             18
14  4.9348     18        88  ...            26            171             61
15  4.1236     13       136  ...             9             16             30
16  3.8363      5       169  ...             0              0              0
17  3.0927      5       141  ...             0              0              0
18  3.8363      5       209  ...             0              1              0
19  5.6784    NaN        11  ...             5             74             20
20  4.6813    NaN       NaN  ...             5            119             35
21  5.3066    NaN        14  ...             9             93             35
22  5.6446    NaN        10  ...             3             55             17
23  3.8870    NaN        28  ...             5            232             31
24  3.0758  7.129  261.8531  ...           0.6            0.4            0.8
25  2.1801  4.535   25.6088  ...           0.1            0.1              0
26  2.1125  5.181      0.34  ...           0.2            0.1            0.1

   1,2,4-Trimethylbenzene 1,2,3-Trimethylbenzene Indane Indene Naphthalene  \
0                    ug/L                   ug/L   ug/L   ug/L        ug/L
1                       1                      1      6      3          38
2                       2                      1     12      3          69
3                     196                    121   1254     41        2207
4                     314                    147   1352     15        5410
5                     284                    134   1031     31        3879
6                     278                    130    814     59        1970
7                     213                    112    617     90         626
8                     169                     80    101    290         745
9                       4                      2      6     27          12
10                      0                      0      1      1          13
11                      0                      0      2      0          10
12                    319                    145     86    944        7168
13                      1                     49    158      7          21
14                    367                    177    416   1126        5693
15                     16                     12     57     28         229
16                      1                      0      2      1          12
17                      1                      0      1      3          16
18                      2                      1     12      3          69
19                    133                     67   1059     45        4797
20                    139                     67   1602      3        7626
21                    202                     98   1185    194        5584
22                     85                     43    425    645        3122
23                    138                     70   1343    115        5676
24                      5                    2.8   40.1     22        51.1
25                    0.2                    0.2    1.1    0.9         8.7
26                    0.3                    0.2    1.4      1        11.9

   metabolites_variety metabolites_concentration
0                  NaN                      ug/L
1                  3.0                         0
2                  4.0                         0
3                 47.0                        90
4                 47.0                       589
5                 43.0                       674
6                 41.0                       514
7                 36.0                       600
8                 23.0                        15
9                 12.0                         6
10                 4.0                         5
11                11.0                         8
12                33.0                        41
13                20.0                       101
14                27.0                        16
15                11.0                         7
16                 2.0                         0
17                 1.0                         0
18                 1.0                         0
19                36.0                       354
20                33.0                       431
21                32.0                       107
22                32.0                        84
23                41.0                       290
24                 1.0                         0
25                 2.0                         0
26                 1.0                         0

[27 rows x 31 columns]
================================================================

**Check on column names:**

In [5]:
column_names_known,column_names_unknown,column_names_standard = mbs.check_columns(data_raw, verbose = True)

==============================================================
 Running function 'check_columns()' on data
==============================================================
29 quantities identified in provided data.
List of names with standard names:
----------------------------------
sample nr  -->  sample_nr
obs_well  -->  obs_well
well type  -->  well_type
Depth  -->  depth
pH  -->  pH
EC  -->  EC
Redox  -->  redoxpot
pE  -->  pE
sulfate  -->  sulfate
ammonium  -->  ammonium
sulfide  -->  sulfide
methane  -->  methane
Fe II  -->  iron2
Mn  -->  manganese
Benzene  -->  benzene
Toluene  -->  toluene
Ethylbenzene  -->  ethylbenzene
P/M Xylene  -->  pm_xylene
O Xylene  -->  o_xylene
Cumene  -->  isopropylbenzene
Propylbenzene  -->  n_propylbenzene
M-Ethyltoluene  -->  3_ethyltoluene
O-Ethyltoluene  -->  2_ethyltoluene
1,2,4-Trimethylbenzene  -->  124_trimethylbenzene
1,2,3-Trimethylbenzene  -->  123_trimethylbenzene
Indane  -->  indane
Indene  -->  indene
Naphthalene  -->  naphthalene
metabolites_variety  -->  metabolites_variety
----------------------------------

Renaming can be done by setting keyword 'standardize' to True.

________________________________________________________________
2 quantities have not been identified in provided data:
---------------------------------------------------------
NPOC
metabolites_concentration
---------------------------------------------------------

Reduction to known quantities can be done by setting keyword 'reduce' to True.

================================================================

**Check on units:**

In [6]:
check_list = mbs.check_units(data_raw, verbose = True)

================================================================
 Running function 'check_units()' on data
================================================================
________________________________________________________________
 All identified quantities given in requested units.
================================================================

**Check on values in columns (transformation to numerical values, handling of nan-values):**

Returns DataFrame without units containing quantities in numerical type.

In [7]:
data_pure = mbs.check_values(data_raw, verbose = True)

================================================================
 Running function 'check_values()' on data
================================================================
WARNING: First row identified as units, has been removed for value check
________________________________________________________________
WARNING: Cound not transform 'sample nr' to numerical values
________________________________________________________________
WARNING: Cound not transform 'obs_well' to numerical values
________________________________________________________________
WARNING: Cound not transform 'well type' to numerical values
________________________________________________________________
WARNING: Cound not transform 'Depth' to numerical values
________________________________________________________________
Quantities with values transformed to numerical (int/float):
-----------------------------------------------------------
pH
EC
Redox
pE
NPOC
sulfate
ammonium
sulfide
methane
Fe II
Mn
Benzene
Toluene
Ethylbenzene
P/M Xylene
O Xylene
Cumene
Propylbenzene
M-Ethyltoluene
O-Ethyltoluene
1,2,4-Trimethylbenzene
1,2,3-Trimethylbenzene
Indane
Indene
Naphthalene
metabolites_variety
metabolites_concentration
================================================================

**Standardization of input data:**

Runs all checks on data, i.e. column names, units and values in one go and returns transformed data with standard column names and valueas in numerical type where possible. Data is not reduced to those columns containing known quantities, i.e. also columns remain with unknown column names. Unknown quantities can be contaminants/metabolites not yet included in analysis scheme or quantities with typo in the name.

In [8]:
data,units = mbs.standardize(data_raw,reduce = False,  verbose=True)
print("Number of columns:", data.shape[1])

================================================================
 Running function 'standardize()' on data
================================================================
 Function performing check of data including:
  * check of column names and standardizing them.
  * check of units and outlining which to adapt.
  * check of values, replacing empty values by nan
    and making them numeric
==============================================================
 Running function 'check_columns()' on data
==============================================================
29 quantities identified in provided data.
List of names with standard names:
----------------------------------
sample nr  -->  sample_nr
obs_well  -->  obs_well
well type  -->  well_type
Depth  -->  depth
pH  -->  pH
EC  -->  EC
Redox  -->  redoxpot
pE  -->  pE
sulfate  -->  sulfate
ammonium  -->  ammonium
sulfide  -->  sulfide
methane  -->  methane
Fe II  -->  iron2
Mn  -->  manganese
Benzene  -->  benzene
Toluene  -->  toluene
Ethylbenzene  -->  ethylbenzene
P/M Xylene  -->  pm_xylene
O Xylene  -->  o_xylene
Cumene  -->  isopropylbenzene
Propylbenzene  -->  n_propylbenzene
M-Ethyltoluene  -->  3_ethyltoluene
O-Ethyltoluene  -->  2_ethyltoluene
1,2,4-Trimethylbenzene  -->  124_trimethylbenzene
1,2,3-Trimethylbenzene  -->  123_trimethylbenzene
Indane  -->  indane
Indene  -->  indene
Naphthalene  -->  naphthalene
metabolites_variety  -->  metabolites_variety
----------------------------------
Identified column names have been standardized
________________________________________________________________
2 quantities have not been identified in provided data:
---------------------------------------------------------
NPOC
metabolites_concentration
---------------------------------------------------------

Reduction to known quantities can be done by setting keyword 'reduce' to True.

================================================================
================================================================
 Running function 'check_units()' on data
================================================================
________________________________________________________________
 All identified quantities given in requested units.
================================================================
================================================================
 Running function 'check_values()' on data
================================================================
WARNING: Cound not transform 'sample_nr' to numerical values
________________________________________________________________
WARNING: Cound not transform 'obs_well' to numerical values
________________________________________________________________
WARNING: Cound not transform 'well_type' to numerical values
________________________________________________________________
WARNING: Cound not transform 'depth' to numerical values
________________________________________________________________
Quantities with values transformed to numerical (int/float):
-----------------------------------------------------------
pH
EC
redoxpot
pE
NPOC
sulfate
ammonium
sulfide
methane
iron2
manganese
benzene
toluene
ethylbenzene
pm_xylene
o_xylene
isopropylbenzene
n_propylbenzene
3_ethyltoluene
2_ethyltoluene
124_trimethylbenzene
123_trimethylbenzene
indane
indene
naphthalene
metabolites_variety
metabolites_concentration
================================================================
================================================================
Number of columns: 31

**Standardization of input data:**

Rerun data standardization without reporting. Now we reduce the data to known/identified quantities and write standard data frame to file
Provides option to save the standardized data to a csv-file.

In [9]:
file_standard = './grift_BTEXIIN_standard.csv'
data,units = mbs.standardize(data_raw,reduce = True, store_csv=file_standard, verbose=False)
print("Number of columns:", data.shape[1])

WARNING: Cound not transform 'sample_nr' to numerical values
________________________________________________________________
WARNING: Cound not transform 'obs_well' to numerical values
________________________________________________________________
WARNING: Cound not transform 'well_type' to numerical values
________________________________________________________________
WARNING: Cound not transform 'depth' to numerical values
________________________________________________________________
Number of columns: 29